# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BlrtRcpp <- function(prior_null, prob_null, n_cluster_null, prior_alt, prob_alt, n_cluster_alt, n_data, n_category, n_outcomes, n_bootstrap, n_rep, n_thread, max_iter, tolerance, seed) {
    .Call(`_poLCAParallel_BlrtRcpp`, prior_null, prob_null, n_cluster_null, prior_alt, prob_alt, n_cluster_alt, n_data, n_category, n_outcomes, n_bootstrap, n_rep, n_thread, max_iter, tolerance, seed)
}

EmAlgorithmRcpp <- function(features, responses, initial_prob, n_data, n_feature, n_category, n_outcomes, n_cluster, n_rep, n_thread, max_iter, tolerance, seed) {
    .Call(`_poLCAParallel_EmAlgorithmRcpp`, features, responses, initial_prob, n_data, n_feature, n_category, n_outcomes, n_cluster, n_rep, n_thread, max_iter, tolerance, seed)
}

ylik <- function(probs, y, obs, items, numChoices, classes) {
    .Call(`_poLCAParallel_ylik`, probs, y, obs, items, numChoices, classes)
}

GoodnessFitRcpp <- function(responses, prior, outcome_prob, n_data, n_category, n_outcomes, n_cluster) {
    .Call(`_poLCAParallel_GoodnessFitRcpp`, responses, prior, outcome_prob, n_data, n_category, n_outcomes, n_cluster)
}

